Website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, json, redirect, url_for
from flask_login import login_required, current_user
from .models import Note, User, Inventory, Cart
from . import db
from .forms import MakeAdminForm, AddItemsForm
from datetime import datetime, timedelta

TIMEOUT_IN_MINUTES = 1
 
views = Blueprint('views', __name__)
@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    items = Inventory.query.all()
    if request.method == "POST":
        note = request.form.get('note')
        if len(note) < 1:
            flash("Note cannot be empty.", category="validation_error")
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash("Note Added", category="success")
        
    return render_template("home.html", user=current_user, items=items)

@views.route('/<int:item_id>', methods=["GET"])
def getitem(item_id):
    item = Inventory.query.get(item_id)
    return render_template('itemcard.html', item=item, user=current_user)

@views.route('/admin', methods=["GET", "POST"])
@login_required
def admin():
    if current_user.is_authenticated:
        if current_user.type == 'admin':
            form2 = MakeAdminForm()
            form = AddItemsForm()
            items = Inventory.query.all()
            time = datetime.now()
            for item in items:
                if item.just_ordered == True:
                    item.just_ordered = False
                    db.session.commit()
                if item.quantity1 < item.min_quantity and item.quantity2 < item.min_quantity:
                    item.quantity1 += item.order_quantity
                    item.quantity2 += item.order_quantity
                    item.just_ordered = True
                    db.session.commit()
                if item.time is not None and datetime.strptime(item.time, '%Y-%m-%d %H:%M:%S.%f') < time:
                    item.has_timedout = True
            if request.method == "POST":
                
                if form.submit.data and form.validate():
                    
                    name = form.name.data
                    img_url = form.img_url.data
                    description = form.description.data
                    price = form.price.data
                    quantity = form.quantity.data
                    min_quantity = form.min_quantity.data
                    order_quantity = form.order_quantity.data
                    
                    item = Inventory(name=name, img_url=img_url, description=description, price=price, quantity1=quantity, quantity2=quantity, on_hold="0", min_quantity=min_quantity, order_quantity=order_quantity)
                    db.session.add(item)
                    db.session.commit()
                    
                    flash("Successfully Added Item to Database!", category='success')
                    return render_template('admin.html', form=form, items=items, form2=form2, user=current_user)
                
                elif form2.submitadmin.data and form2.validate():
                    
                    email = form2.email.data
                    user = User.query.filter_by(email=email).first()
                    if user:
                        return render_template('make_admin.html', email=email, user=current_user)
                    else:
                        flash("User does not exist.", category="validation_error")
                        return render_template('admin.html', form=form, items=items, form2=form2, user=current_user)
                else:
                    flash("Form didn't pass validation.", category='validation_error')
                    return render_template('admin.html', form=form, items=items, form2=form2, user=current_user)
                
            elif request.method == "GET":
                return render_template('admin.html', form=form, items=items, form2=form2, user=current_user)
        else:
            return redirect(url_for('views.home'))
    else:
        return redirect(url_for('views.home'))

@views.route('/delete-note', methods=["POST"])
def delete_note():
    note = json.loads(request.data)
    note_id = note['note_id']
    note = Note.query.get(note_id)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            return jsonify({})

@views.route('/cart', methods=["GET", "POST"])
@login_required
def cart():
    user_id = current_user.id
    cart_items = Cart.query.filter_by(user_id=user_id).all()
    items = []
    final_total = 0
    for item in cart_items:
        inv_item = Inventory.query.get(item.item_id)
        inv_item.quantity1 = item.quantity
        final_total += inv_item.price * inv_item.quantity1
        items.append(inv_item)
    return render_template('cart.html', cart=items, final_total=final_total, user=current_user)

@views.route('/<int:item_id>/add_to_cart', methods=["POST", "GET"])
def add_to_cart(item_id):

    if current_user.is_authenticated:
        user_id = current_user.id
        cart_item = Cart.query.filter_by(item_id=item_id, user_id=user_id).first()
        if cart_item:
            cart_item.quantity += 1
            db.session.add(cart_item)
            db.session.commit()
            flash("Item Added.", category="success")
        else:
            cart = Cart(item_id=item_id, user_id=user_id, quantity=1)
            db.session.add(cart)
            db.session.commit()
            flash("Item Added.", category="success")
    else:
        flash('You need to log in to add items to your cart', category='danger')
        return redirect(url_for('auth.loginPage'))
    return redirect(url_for('views.home'))

@views.route('/cart/<int:item_id>/remove', methods=["POST", "GET"])
def remove_from_cart(item_id):
    user_id = current_user.id
    cart_item = Cart.query.filter_by(item_id=item_id, user_id=user_id).first()

    if not cart_item:
        return redirect(url_for('views.cart'))

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        db.session.add(cart_item)
        db.session.commit()
    else:
        db.session.delete(cart_item)
        db.session.commit()

    return redirect(url_for('views.cart'))

@views.route('/<int:item_id>/found', methods=["POST", "GET"])
def items_found(item_id):
    item = Inventory.query.filter_by(id=item_id).first()
    item.time = None
    item.quantity1 += int(item.on_hold)
    item.on_hold = 0
    db.session.commit()
    return redirect(url_for('views.admin'))

@views.route('/<int:item_id>/lost', methods=["POST", "GET"])
def items_lost(item_id):
    item = Inventory.query.filter_by(id=item_id).first()
    item.time = None
    item.quantity2 -= int(item.on_hold)
    item.on_hold = 0
    db.session.commit()
    return redirect(url_for('views.admin'))

@views.route('/cart/clear', methods=["POST", "GET"])
def clear_cart():
    user_id = current_user.id
    cart_items = Cart.query.filter_by(user_id=user_id).all()

    for cart_item in cart_items:
        db.session.delete(cart_item)
        db.session.commit()

    return redirect(url_for('views.cart'))

def message_flasher(error_items, success_items):
    print(success_items, error_items)
    if error_items == []:
        if len(success_items) > 1:
            flash(", ".join(success_items) + " were successfully purchased.", category="success")
        elif len(success_items) == 1:
            flash(success_items[0] + " was purchased.", category="success")
        return True
    else:
        if len(success_items) > 1:
            flash(", ".join(success_items) + " were successfully purchased.", category="success")
        elif len(success_items) == 1:
            flash(success_items[0] + " was purchased.", category="success")

        if len(error_items) > 1:
            flash(", ".join(error_items) + " could not be purchased.", category="validation_error")
        elif len(error_items) == 1:
            flash(error_items[0] + " could not be purchased.", category="validation_error")

        return False

@views.route('/cart/checkout', methods=["POST", "GET"])
def checkout():
    user_id = current_user.id
    cart_items = Cart.query.filter_by(user_id=user_id).all()
    
    if current_user.type == "admin":
        success_items = []
        error_items = []
        for cart_item in cart_items:
            item = Inventory.query.filter_by(id=cart_item.item_id).first()
            if item.quantity1 >= cart_item.quantity and item.quantity2 >= cart_item.quantity:
                item.reduce_quantity1(cart_item.quantity)
                item.reduce_quantity2(cart_item.quantity)
                db.session.delete(cart_item)
                db.session.commit()
                success_items.append(item.name)
            else:
                error_items.append(item.name)
            
        if message_flasher(error_items=error_items, success_items=success_items):
            return redirect(url_for('views.checkout_success'))
        else:
            return redirect(url_for('views.checkout_failure'))

    elif current_user.type == "Sensor":
        #Add items on hold.
        success_items = []
        error_items = []
        for cart_item in cart_items:
            item = Inventory.query.filter_by(id=cart_item.item_id).first()
            if item.quantity1 >= cart_item.quantity:
                item.reduce_quantity1(cart_item.quantity)
                item.increase_onhold(cart_item.quantity, TIMEOUT_IN_MINUTES)
                db.session.delete(cart_item)
                db.session.commit()
                success_items.append(item.name)
            else:
                error_items.append(item.name)
        
        if message_flasher(error_items=error_items, success_items=success_items):
            return redirect(url_for('views.checkout_success'))
        else:
            return redirect(url_for('views.checkout_failure'))
    

Website/templates/admin.html
{% extends "base.html" %} {% block title %} Admin Control Panel {% endblock %}
{% block content %}

<h1 style="text-align:center; margin:4.5rem 0 2rem 0; font-weight:500; text-shadow:0 0 0.1em rgb(255, 255, 255)">Make Admin:</h1>
<div>
     <form method="POST" class="container col-4">
         {{ form.hidden_tag() }}
         {{ form2.email(style="margin-top:1rem", class='form-control', placeholder='Please enter email.') }}
         {{ form2.submitadmin(style="margin-top:1rem", value="Make Admin") }}
     </form>
</div>
<h1 style="text-align:center; margin:2rem 0; font-weight:500; text-shadow:0 0 0.1em rgb(255, 255, 255)">Add items to database</h1>
   <div>
        <form method="POST" class="container col-4">
            {{ form.hidden_tag() }}
            {{form.name(style="margin-top:1rem", class='form-control', placeholder='Enter product name.')}}
            {{form.img_url(style="margin-top:1rem", class='form-control', placeholder='Enter url for product image.')}}
            {{form.description(style="margin-top:1rem", class='form-control', placeholder='Enter product description.')}}
            {{form.price(style="margin-top:1rem", class='form-control', placeholder='Enter price.')}}
            {{form.quantity(style="margin-top:1rem", class='form-control', placeholder='Quantity')}}
            {{form.min_quantity(style="margin-top:1rem", class='form-control', placeholder='Minimum Quantity')}}
            {{form.order_quantity(style="margin-top:1rem", class='form-control', placeholder='Auto Order Quantity')}}
            {{form.submit(style="margin-top:1rem", value="Add to DB")}}
        </form>
   </div>
   <h1 style="text-align:center; margin:2rem 0; font-weight:500; text-shadow:0 0 0.1em rgb(255, 255, 255)">Inventory Dashboard:</h1>
   <div class="d-flex justify-content-center flex-wrap">

    {% for item in items %}
        <div class="card" style="width: 18rem; margin:1rem; border: 1px solid black">
            <a class="text-dark text-decoration-none" href="{{ url_for('views.getitem', item_id=item.id) }}">
            <img style="width:80%; margin: 0 auto; padding-left: 3rem" src="{{item.img_url}}" class="card-img-top" alt="{{ item.title }}">
            <div class="card-body">
                <h5 class="card-title">{{ item.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
            <li class="list-group-item"></li>
            <li class="list-group-item">{{ item.description }}</li>
            <li class="list-group-item"><strong>Price:</strong> ${{ item.price }}</li>
            <li class="list-group-item"> Database1 : {{item.quantity1}}</li>
            <li class="list-group-item"> Database2 : {{item.quantity2}}</li>
            <li class="list-group-item"> On Hold : {{item.on_hold}}</li>
            {% if item.has_timedout == true %}
                <li class="list-group-item"> TIMEOUT. Please check for missing items. </li>
                <button type="button" class="btn btn-success btn-sm">
                    <a href="/{{item.id}}/found" class="card-link" style="color: white; text-decoration: none"> Items Found </a>
                </button>
                <button type="button" class="btn btn-danger btn-sm">
                    <a href="/{{item.id}}/lost" class="card-link" style="color: white; text-decoration: none"> Items Lost </a>
                </button>
            {% endif %}
            {% if item.just_ordered == true %}
                <li class="list-group-item"> Item was under minimum quantity. Item has beed auto-ordered. </li>
            {% endif %}
            </ul></a>
            <div class="card-body">
                
                <button type="button" class="btn btn-danger btn-sm">
                    <a href="/{{item.id}}/delete" class="card-link" style="color: white; text-decoration: none">Delete From Inventory</a>
                </button>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock %}

Website/templates/base.html
<!DOCKTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport">
        

        <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title> {% block title %} Home {% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
            <button 
            class="navbar-toggler" 
            type="button" 
            data-toggle="collapse" 
            data-target="#navbar"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    {% if not user.is_authenticated %}
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    <a class="nav-item nav-link" id="sign-up" href="/sign-up">Sign Up</a>
                    {% else %}
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                    <a class="nav-item nav-link" id="home" href="/">Home</a>
                    {% if user.type == 'admin' %}
                    <a class="nav-item nav-link" id="user-type" href="/admin"> Control Panel </a>
                    {% endif %}
                    <a class="nav-item nav-link disabled" id="user-type" href="/"> {{ user.type }} </a>
                    <a class="nav-item nav-link disabled" id="user-name" href="/">Hi, {{ user.firstName }}</a>
                    <a class="nav-item nav-link" id="cart" href="/cart"> Cart <i class="fa fa-shopping-cart"></i></a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
          {% if category=="validation_error" %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endif %}
          {% endfor %}
        {% endif %}
        {% endwith %}

<div class="container">{% block content %} {% endblock %}</div>
        <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>

    <script
    type="text/javascript"
    src="{{ url_for('static', filename='index.js') }}"
    ></script>
    </body>
</html>

Website/templates/cart.html
{% extends 'base.html' %} {% block title %} Cart {% endblock %}
{% block content %}
<h1 style="text-align:center; margin:4.5rem 0 2rem 0; font-weight:500; font-size: 60px; text-shadow:0 0 0.1em rgb(255, 255, 255)">Cart:</h1>
<div class="d-flex justify-content-center flex-wrap">
    {% for inv_item in cart %}
    <div class="card" style="width: 14rem; margin:0; border: 1px solid black">
        <a class="text-dark text-decoration-none" href="{{ url_for('views.getitem', item_id=inv_item.id) }}">
            <img style="width:80%; margin: 0 auto; padding-left: 3rem" src="{{ inv_item.img_url }}" class="card-img-top"
                alt="{{ inv_item.name }}">
            <div class="card-body">
                <h5 class="card-title">{{ inv_item.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Quantity: {{ inv_item.quantity1 }}</li>
                <li class="list-group-item">Price: {{ inv_item.price * inv_item.quantity1 }}</li>
            </ul>
        </a>
        <div class="card-body">
            <form id="remove_from_cart_form_{{ inv_item.id }}" action="{{ url_for('views.remove_from_cart', item_id=inv_item.id) }}" method="post">
                <button type="submit" class="btn btn-danger" form="remove_from_cart_form_{{ inv_item.id }}">Remove</button>
            </form>
        </div>
    </div>
    {% endfor %}
</div>

<div class="card text-center" style="width: 100%; border: 1px solid black">
    <div class="card-body">
        <h5 class="card-title">Total:</h5>
        <p class="card-text">${{final_total}}</p>
        {% if cart != [] %}
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Clear Cart
            </button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal1">
                Checkout
            </button>
        {% endif %}

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">This will clear all items in your cart!</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Are you sure?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <a class="btn btn-danger" href="{{ url_for('views.clear_cart') }}">Clear Cart</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Thank you for shopping with us.</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Click 'Submit' to complete your order.
                    </div>
                    <div class="modal-footer">
                        <a class="btn btn-primary" href="{{ url_for('views.checkout') }}">Submit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 

{% endblock %}

Website/templates/checkout_failure.html
{% extends "base.html" %} {% block title %} Success {% endblock %}
{% block content %}

<div class="container">
    <div class="center", style="display: flex; justify-content: center;">
        <img src="{{url_for('static', filename='error.png')}}", width="300vw", height="180vw", class="center">
    </div>
    <div class="center", style="display: flex; justify-content: center;">
        <h1>Oops. That did not go as planned.</h1>
    </div>
    <div class="center", style="display: flex; justify-content: center;">
        <a class="btn btn-primary" href="{{ url_for('views.home') }}"> Home </a>
    </div>
</div>


{% endblock %}

Website/templates/checkout_success.html
{% extends "base.html" %} {% block title %} Success {% endblock %}
{% block content %}

<div class="container">
    <div class="center", style="display: flex; justify-content: center;">
        <img src="{{url_for('static', filename='check.jpg')}}", width="300vw", height="180vw", class="center">
    </div>
    <div class="center", style="display: flex; justify-content: center;">
        <h1>Thankyou for shopping with us.</h1>
    </div>
    <div class="center", style="display: flex; justify-content: center;">
        <a class="btn btn-primary" href="{{ url_for('views.home') }}"> Home </a>
    </div>
</div>


{% endblock %}

Website/templates/home.html
{% extends "base.html" %} {% block title %} Home {% endblock %}
{% block content %}
   <h3 style="text-align:center; margin:2 rem 0 2rem 0; font-weight:500; text-shadow:0 0 0.1em rgb(255, 255, 255)">Store Home</h3>
   <div class="d-flex justify-content-center flex-wrap">

    {% for item in items %}
        <div class="card" style="width: 18rem; margin:1rem; border: 1px solid black">
            <a class="text-dark text-decoration-none" href="{{ url_for('views.getitem', item_id=item.id) }}">
            <img style="width:80%; margin: 0 auto; padding-left: 3rem" src="{{item.img_url}}" class="card-img-top" alt="{{ item.title }}">
            <div class="card-body">
                <h5 class="card-title">{{ item.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
            <li class="list-group-item"></li>
            <li class="list-group-item">{{ item.description }}</li>
            <li class="list-group-item"><strong>Price:</strong> ${{ item.price }}</li>
            </ul></a>
            <div class="card-body">
                <button type="button" class="btn btn-success btn-sm">
                    <a href="/{{item.id}}/add_to_cart" class="card-link" style="color:white; text-decoration:none">Add to Cart</a>
                </button>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

Website/templates/inventory.html
{% extends 'base.html' %}
{% block content %}
   <h1 style="text-align:center; margin:4.5rem 0 2rem 0; font-weight:500; font-size: 120px; text-shadow:0 0 0.1em rgb(255, 255, 255)">Meanitems</h1>
   <div class="d-flex justify-content-center flex-wrap">

    {% for item in items %}
        <div class="card" style="width: 18rem; margin:1rem; border: 1px solid black">
            <a class="text-dark text-decoration-none" href="{{ url_for('views.getitem', item_id=item.id) }}">
            <img style="width:80%; margin: 0 auto; padding-left: 3rem" src="{{item.img_url}}" class="card-img-top" alt="{{ item.title }}">
            <div class="card-body">
                <h5 class="card-title">{{ item.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
            <li class="list-group-item"></li>
            <li class="list-group-item">{{ item.description }}</li>
            <li class="list-group-item"><strong>Price:</strong> ${{ item.price }}</li>
            </ul></a>
            <div class="card-body">
                <button type="button" class="btn btn-success btn-sm">
                    <a href="/{{item.id}}/add_to_cart" class="card-link" style="color:white; text-decoration:none">Add to Cart</a>
                </button>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

Website/templates/itemcard.html
{% extends 'base.html' %}
{% block content %}
<div class="card my-6 mx-auto rounded" style="max-width: 50%; margin-top: 5rem; border: 1px solid black">
    <div class="row g-0">
        <div class="col-md-4 rounded">
            <img style="width: 100%" src="{{item.img_url}}" class="img-fluid rounded-start" alt="{{ item.title }}">
        </div>
        <div class="col-md-8 rounded">
            <div class="card-body rounded">
                <h5 class="card-title mt-4 mb-4">{{ item.name }}</h5>
                <div class="card-text mt-4 mb-4">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ item.description }}</li>
                        <li class="list-group-item"><strong>Price:</strong> ${{ item.price }}</li>
                    </ul>
                </div>
                <div class="d-grid gap-2 col-6 mx-auto">
                    <button type="button" class="btn btn-success btn-sm">
                        <a href="/{{item.id}}/add_to_cart" class="card-link" style="color:white; text-decoration:none">Add to Cart</a>
                      </button>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

Website/templates/login.html
{% extends "base.html" %} {% block title %} Login {% endblock %}
{% block content %}
<form method="post">
    <h3 align="center"> Login </h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter a Password">
    </div>
    <br>
    <button type="submit" class="btn btn-primary"> Login </button>
{% endblock %}

Website/templates/logout.html
{% extends "base.html" %} {% block title %} Logout {% endblock %}
{% block content %}
<h1> Logged Out </h1>
{% endblock %}

Website/templates/make_admin.html
{% extends "base.html" %} {% block title %} Admin Control Panel {% endblock %}
{% block content %}
<h1 style="text-align:center; margin:4.5rem 0 2rem 0; font-weight:500; text-shadow:0 0 0.1em rgb(255, 255, 255)">Make Admin:</h1>
<div class="card" style="width: 18rem; border: 1px solid black; margin:0 auto">
    <div class="card-body">
      <h5 class="card-title" style="text-align:center">Make "{{ email }}" an Admin?</h5>
      <a href="/make_admin/{{ email }}" class="btn btn-success btn-sm" style="margin-left: 5rem">Make Admin</a>
    </div>
  </div>

{% endblock %}

Website/templates/note.html
{% extends "base.html" %} {% block title %} Home {% endblock %}
{% block content %}

<h1 align="center"> Notes </h1>
<ul class="list-group list-group-flush" id="notes"> 
    {% for note in user.notes %}
    <li class="list-group-item"> 
        {{ note.data }} 
        <button type="button" class="close" onClick="delete_note({{ note.id }})">
            <span aria-hidden="true">&times;</span>
        </button>
    </li>
    {% endfor %}
</ul>
<form method="post">
    <textarea name="note" id="note" class="form-control"></textarea>
    <div align="center">
        <br>
        <button type="submit" class="btn btn-primary"> Add Note </button>
    </div>
</form>

{% endblock %}

Website/templates/signup.html
{% extends "base.html" %} {% block title %} sign-up {% endblock %}
{% block content %}
<form method="post">
    <h3 align="center"> Sign Up </h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email">
    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name">
    </div>
    <div class="form-group">
        <label for="lastName">Last Name</label>
        <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Enter Last Name">
    </div>
    <div class="form-group">
        <label for="phone">Phone Number</label>
        <input type="tel" class="form-control" id="phone" name="phone" placeholder="Enter Phone number.">
    </div>
    <div class="form-group">
        <label for="user-type">User type</label>
        <select name="user-type", method="GET", action="/", class="form-control">
        {% for user_type in user_types %}
        <option value= "{{user_type}}" SELECTED>{{user_type}}</option>"
        {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter a Password">
    </div>
    <div class="form-group">
        <label for="password2">Check Password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Re-Enter Password">
    </div>
    <br>
    <button type="submit" class="btn btn-primary"> Submit </button>
{% endblock %}